### PR TITLE
Update to use SDK v3.

### PR DESCRIPTION
**Pull request by bangpound**
Consul PHP SDK version 3 has `SensioLabs\Consul\Services\KVInterface` and the implementation
is declared final. This imposes small but fundamentally breaking changes to the project.

### CODE REVIEW

**Comment by bangpound** [comment]
Please let me know if you'd like to consider this PR. I realize it's a breaking change even though it's so minor.

**Comment by Nek-** [comment]
composer.lock should not be commited. You probably should add a commit to remove it and add a line about in the .gitignore

**Comment by bangpound** [comment]
@nek- You’re not wrong, but composer.lock is already committed to this project. If this PR doesn’t update the lock file, the CI tests fail. You are welcome to submit your own pull request to remove composer.lock.

**Comment by Nek-** [comment]
I took a look and indeed there are some problems with the lib. Here is a branch working as expecting. https://github.com/Nek-/consul-php-envvar/commits/master

**Comment by petrepatrasc** [comment]
Thank you @bangpound, merged!

**Pull request merged**
